version: '3.1'
services:

  peppermint_user_api_service:
    container_name: peppermint_user_api_service
    restart: always
    environment:
      - 'JAVA_TOOL_OPTIONS=-Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx6144M -Xms1024M -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact'
    image: registry.peppermint.com/peppermint_user_api_service:1.0.0
    volumes:
      - ~/.m2:/root/.m2
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/environment:/etc/environment:ro
      - /etc/hosts:/etc/hosts:ro
      - ~/logs:/root/logs
    ports:
      - "8080:8080"

networks:
  PEPPERMINIT-SYSTEM-NETWORK:
    external: true
